
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Poetry Package
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry build
    - name: Publish Poetry Package
      env:
        password: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --username amtago --password "$env:password"